image: python:3.7

stages:
  - "lint"
  - "build"

before_script:
  - python -m pip install -r requirements.txt

pylint:
  stage: "lint"
  tags:
    - "qt-runner"
  script:
    - python -m pip install pylint
    - pylint --errors-only Plot/ Network/ uart/ utils/

build:
  stage: "build"
  tags:
    - "qt-runner"
  script:
    - python setup.py

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/




