stages:
  - "lint"
  - "build"


.set_tags: &set-tags  
  tags:
    - qt-win-runner1

pylint:
  <<: *set-tags
  stage: "lint"
  script:
    - powershell.exe -File pylint.ps1

build:
  <<: *set-tags
  stage: "build"

  script:
    - powershell.exe -File build.ps1

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/




