stages:
  - "lint"
  - "build"

before_script:
  # - conda create --name myenv
  - conda init powershell
  - conda activate pyqt 

.set_tags: &set-tags  
  tags:
    - qt-win-runner1

pylint:
  <<: *set-tags
  stage: "lint"
  script:
    - python -m pip install pylint'
    - pylint --errors-only Plot/ Network/ uart/ utils/'

build:
  <<: *set-tags
  stage: "build"

  script:
    - python setup.py'

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/




